apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: frontend
        image: 891376955975.dkr.ecr.ap-south-1.amazonaws.com/frontend:9
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://a363f09d06e7c49fe863658d78c28de8-1265141247.ap-south-1.elb.amazonaws.com/api/tasks"  # Replace <load-balancer-dns-name> with actual DNS
        ports:
        - containerPort: 3000

